CREATE TABLE IF NOT EXISTS user (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS refresh_token (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  user_agent VARCHAR(512) NULL,
  CONSTRAINT refresh_token_user_fk FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS publisher (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  slug VARCHAR(255) NOT NULL UNIQUE,
  rel_path VARCHAR(768) NOT NULL,
  background_image VARCHAR(768) NULL,
  comic_count INT UNSIGNED NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS comic (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  publisher_id BIGINT UNSIGNED NOT NULL,
  rel_path VARCHAR(768) NOT NULL UNIQUE,
  filename VARCHAR(768) NOT NULL,
  original_filename VARCHAR(768) NOT NULL,
  extension VARCHAR(8) NOT NULL,
  number INT NULL,
  title_resolved VARCHAR(768) NOT NULL,
  archive_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  archive_mtime INT UNSIGNED NOT NULL DEFAULT 0,
  archive_type ENUM('zip', 'rar', 'none') NOT NULL DEFAULT 'none',
  is_solid BOOLEAN NOT NULL DEFAULT FALSE,
  page_count INT NULL,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  scanned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  indexed_at DATETIME NULL,
  CONSTRAINT comic_publisher_fk FOREIGN KEY (publisher_id) REFERENCES publisher(id),
  FULLTEXT KEY comic_search_ftx (title_resolved, filename)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS reading_progress (
  user_id BIGINT UNSIGNED NOT NULL,
  comic_id BIGINT UNSIGNED NOT NULL,
  page_index INT UNSIGNED NOT NULL DEFAULT 0,
  total_pages INT UNSIGNED NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, comic_id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (comic_id) REFERENCES comic(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
