CREATE TABLE IF NOT EXISTS scan_run (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  status ENUM('queued', 'running', 'completed', 'failed') NOT NULL DEFAULT 'queued',
  added INT UNSIGNED NOT NULL DEFAULT 0,
  updated INT UNSIGNED NOT NULL DEFAULT 0,
  removed INT UNSIGNED NOT NULL DEFAULT 0,
  errors_json JSON NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
