CREATE TABLE IF NOT EXISTS page_cache (
  ck CHAR(40) PRIMARY KEY,
  bytes BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_hit DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY page_cache_lru (last_hit)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
