CREATE TABLE IF NOT EXISTS bookmark (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  comic_id BIGINT UNSIGNED NOT NULL,
  page_index INT UNSIGNED NOT NULL,
  note VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (comic_id) REFERENCES comic(id) ON DELETE CASCADE,
  KEY bookmark_user_comic (user_id, comic_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_setting (
  user_id BIGINT UNSIGNED NOT NULL,
  `key` VARCHAR(190) NOT NULL,
  value_json JSON NOT NULL,
  PRIMARY KEY (user_id, `key`),
  FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
